string=input("enter the string:")
character=len(string)
word=string.split()
word=string.count(string)
print("no of character in string:")
print(character)
print("no of words in string:")
print(word)
